# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='未填写', max_length=50, unique=True, verbose_name='姓名'),
        ),
    ]
